# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'memo_app_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for memo_app_test


pod 'RxSwift'
pod 'RxCocoa'
pod 'NSObject+Rx'
pod 'SwipeCellKit'

end
