language: objective-c
osx_image: xcode10.1

cache:
  - bundler
  - cocoapods

env:
  global:
    - WORKSPACE="RxTodo.xcworkspace"
    - IOS_SDK="iphonesimulator12.1"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone XS,OS=12.1"
  matrix:
    - SCHEME="RxTodo"        SDK="$IOS_SDK"      ACTION="test"

install:
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install

script:
  - set -o pipefail && xcodebuild clean $ACTION -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$IOS_DESTINATION" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
